site_name: 'Blog @cdivriotis97'
site_dir: /var/www/mkdocs
site_author: 'Constantin Divriotis'
site_url: https://ganymede.blog/
site_description: >-
  Constantin Divriotis | Playground
repo_url: https://github.com/cdivriotis97/ganymede
theme:
  name: material
  custom_dir: overrides
  #logo: assets/images/logo.png
  #favicon: assets/images/favicon.ico
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference
  features:
    - navigation.indexes
    - navigation.path
    - search.suggest
    - search.share
    - content.action.edit
    - content.code.copy
    - content.code.select
    - content.tabs.link
plugins:
  - glightbox
  - search:
      lang: en      

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Miscellaneous:
    - About Me: guides/miscellaneous/cv.md
    - My Notes: guides/miscellaneous/notes.md
  - AIX Cookbook:
    - AIX Concepts: guides/aix/general.md
    - Troubleshooting: guides/aix/troubleshooting.md
    - Useful Commands: guides/aix/commands.md
  - Linux Cookbook: 
    - Linux Concepts: guides/linux/general.md
    - Steam on Linux: guides/linux/steam.md
    - CoreOS: guides/linux/coreos.md
    - Podman Quadlet: guides/linux/podman-quadlet.md
    - Troubleshooting: guides/linux/troubleshooting.md
    - Useful Commands: guides/linux/commands.md
    - SSH: guides/linux/ssh.md
  - Storage Cookbook:
    - Backup Configuration with Ansible: guides/storage/backup_with_ansible.md
    - Troubleshooting: guides/storage/troubleshooting.md
  - Monitoring Cookbook:
    - Zabbix: guides/monitoring/zabbix.md
  - Network Cookbook:
    - Backup Configuration with Ansible: guides/network/backup_with_ansible.md


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cdivriotis97
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@cdivriotis

copyright: Copyright &copy; 2026 Constantin Divriotis | Powered by GNU GPLv3